server:
  port: 8080
spring:
  application:
    name: "ms-authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  r2dbc-postgresql:
    host: "localhost"
    port: 5432
    database: ""
    username: ""
    password: ""
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
